name: shaksite
region: nyc
services:
  # Combined Backend + Frontend Service
  - name: web
    type: web
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${APP_URL}
    health_check:
      http_path: /api/quotes
    routes:
      - path: /
