name: shaksite
region: nyc

services:
  # Combined Backend + Frontend Service
  - name: web
    type: web
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    health_check:
      http_path: /api/quotes
    # Mount volumes for persistent storage
    mounts:
      - path: /app/uploads
        source: shaksite-data
      - path: /app/data
        source: shaksite-json

# Define volumes for persistent storage
volumes:
  - name: shaksite-data
  - name: shaksite-json
